# Generated by Django 4.1.1 on 2022-12-23 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('deposit_amount', models.IntegerField()),
                ('withdraw_amount', models.IntegerField()),
                ('rank', models.CharField(max_length=50)),
            ],
        ),
    ]
